### ISSUE TITLE
legomario i know what BRVLY code is.

### ISSUE THREAD

**Issue by quinman24** [mutesplash/legomario#2]
hay mutesplash I know what the RGB code BRVLY is. its the code for the new Lego bowser set whare you scan the code to initializes the fight, and then scan yellow bricks to defeat him.

![lego bowser BRVLY-1](https://user-images.githubusercontent.com/95267963/200213144-57a19479-31c0-497d-bd3e-06a6bde2e141.png)

**Comment by quinman24** [comment]
just fyi this code ![lego bowser BRVLY-1](https://user-images.githubusercontent.com/95267963/200213144-57a19479-31c0-497d-bd3e-06a6bde2e141.png) BRVLY is from the lego the mighty bowser.

**Comment by mutesplash** [comment]
Verified. Fixed.

**Comment by quinman24** [comment]
can I suggest BIG_BOW for the name of BRVLY aka MIGTYBOW?

**Comment by mutesplash** [comment]
Only because you opened this issue 😉

**Comment by mutesplash** [comment]
Hm, looks too much like a literal big bow, though.  BGBOWSER or BIGBOWSR ?

**Comment by quinman24** [comment]
BIGBOWSR is fine thank you.
