### ISSUE TITLE
Color Code for 221 not reflected in BTLegoMario.py

### ISSUE THREAD

**Issue by tomalphin** [mutesplash/legomario#3]
In BTLegoMario.py - there is no color defined in solid_colors for value = 221.  That's the value the color scanner reports when I put mario onto a 222.Light Purple (Bright Pink), 221. Bright Purple (Dark Pink), or 124. Bright Reddish Violet (Magenta) LEGO Brick.

Given the suspicious correlation to LEGO official color code 221 - I think it is meant to be Bright Pink (LEGO Official name) / Dark Pink (BrickLink name).

**Comment by tomalphin** [comment]
I also discovered that code 119 is reported from Peach/Mario when placed on a Bright yellowish Green / Lime LEGO brick..  This again corresponds to the official / internal LEGO Color codes.

**Comment by tomalphin** [comment]
It also recognizes 324 - which is "Medium Lavender".

I also saw a note in the code that you couldn't get blue to trigger.  I am seeing the "blue" message when on 321 - Dark Azur color, but not on 23. Bright Blue (which is the classic LEGO blue color)

**Comment by mutesplash** [comment]
I will run through some of the colors and cross check this week!

**Comment by mutesplash** [comment]
Colors were present in the 5.3 update. Wonder when they updated.

**Comment by mutesplash** [comment]
Fixed in the latest update!  What counts for pink is... interesting.  Coral (353) counts as red

Also added some other stuff.  The whole cyan ice interaction I don't quite understand.
