### ISSUE TITLE
Why do custom barcodes with a black strip report as "___U___" and 32767

### ISSUE THREAD

**Issue by tomalphin** [mutesplash/legomario#4]
I have been printing a bunch of custom barcodes to try and identify patterns that don't start with BR or GR, as well as trying to determine the missing color that is hypothesized to be Black.  

_(No luck identifying alternative to BR or GR, but my best guess if they need more codes is that they would start supporting "PR" or simply add support for the missing color code, likely black.  Of course, since they can change the firmware, they can change the barcode reading, possibly also adding many more colors, or adding support for 6-line codes.)_

This leads to the question, I've made a couple variants with a Black stripe, and they all semi-reliably report back in Scan.py as "__U__" and 32767.  Is this value raw data from the Bluetooth protocol from Mario, or something that the python app is deriving from the data it receives?

examples I have tested ("K" for Black.)
- GRLBK
- GRPBK

Thoughts?

**Comment by mutesplash** [comment]
https://github.com/mutesplash/legomario/blob/0a009cc623a3af04909ee8524ecef33f720f4ae3/BTLegoMario.py#L993

If it's constantly returning something like (--U-- 32767) for anything with a black color, then 32767 must be the number Lego Mario returns over Bluetooth for a recognized barcode, but invalid code, which, is interesting in and of itself.  That is the maximum positive 16-bit signed integer (01111111 11111111).  My script is translating that invalid number into "--U--"

--U-- means it wasn't "in" the codespace: It's not a valid code for the BR, GR "rules."  The rules are fairly predictable, as generate_gr_codespace() and generate_br_codespace() correctly predict the integer values.  I only detected the BR codespace after the tiles were revealed in the app.  There's probably some other way to generate the codes, and the unprintable "color" is just an artifact of the way I've created the algorithm.  The reason I dump the binary in codespace.txt is to assist in detecting patterns to reveal another way of generating the codespace.

You can generate the codespace.txt file with this:
```
from BTLegoMario import BTLegoMario
import os
from pathlib import Path
import json

json_code_file = "mariocodes.json"
code_data = None
check_file = Path(os.path.expanduser(json_code_file))
if check_file.is_file():
	with open(check_file, "rb") as f:
		try:
			code_data = json.loads(f.read())
		except ValueError as e:  # also JSONDecodeError
			print("Unable to load code translation JSON:"+str(e))

if not code_data:
	print("Known code database (mariocodes.json) NOT loaded!")

mario = BTLegoMario(code_data)
print("i\tcode\tmirror\tlabel\t\tscanner hex\tbinary")
print("-----------------------------------------------------------------")

BTLegoMario.print_codespace()
````

**Comment by mutesplash** [comment]
I changed the code to return an error in the message queue instead of returning the bogus code.

**Comment by tomalphin** [comment]
Thanks for updating the logic - I will try the new code tonight...

regarding this comment you made when changing the code:
> "Instead of making up a code event. @tomalphin says the scanner returns max signed 16-bit int when you slap a bad color (ie: black) into a code with a GR prefix."

I have tried a lot of additional colors besides the known good set (RGBTVLPY) and the only other color which yields a response is Black.  That is interesting and corroborates the theory that Black is the missing color, they just have not chosen to utilize it yet in the FW.  

I wonder if the reason they decided to exclude Black is that it seems to decrease scanning reliability a bit - codes with a black stripe don't scan quite as reliably as others - maybe the black stripe is messing up the white balance / brightness sensing of the tiny barcode reader camera.

My hypothesis if they did end up using black in the future as the missing color is that they would use a very dark gray instead of true black.  That might interfere less with scanning other colors.  (C:0, M:0, Y:0, K50 - middle gray doesn't scan most of the time, but sometimes is read as Violet - if I remember correctly from my testing a few days ago...)

**Comment by mutesplash** [comment]
Ok, so what you're saying is the only color that "fools" the scanner into sending the color codes through the bluetooth message path is black and the other colors just die somewhere inside Mario.  When you scan bad colors, do they make any indication on the screen or make noise?

Might be interesting to plot the current colors in a color space and see if there are voids anywhere.

I'll make a note about black in the code.  Did you have any method for testing the other colors?

**Comment by tomalphin** [comment]
> Might be interesting to plot the current colors in a color space and see if there are voids anywhere.

Correct - I took the 8 known colors and inspected them in CMYK colorspace. It was interesting to see that almost every color had a value of either 0, 50, or 100 in the C/M/Y positions, and a K (Black) of 0.  the 0 value in K indicates that they are all 100% saturation colors, which makes sense for a scanning system.

When I include Black and Gray, there are another 10 possible combinations of the 0/50/100 in those three channels.  I created a test card with every possible color value.  Photo Attached.

> Ok, so what you're saying is the only color that "fools" the scanner into sending the color codes through the bluetooth message path is black and the other colors just die somewhere inside Mario. When you scan bad colors, do they make any indication on the screen or make noise?

**Correct** - I have tried all of the color combinations mentioned above as the 5th stripe in a custom printed barcode.  

![PXL_20221230_215840330](https://user-images.githubusercontent.com/66934882/210114891-73c73923-7a91-44f2-8a1c-342c73899e51.jpg)


_I also tried a couple known LEGO color values that don't align as well on 0/50/100 such as Light Tan, and it also did not do anything special._

**A few of these 'extra' colors scan as a similar color:**
- GRLB[Magenta] barcode scans as "GRLBP") - indicating that the scanner sees Magenta (C:0, M:100, Y:0, K:0) as if it were Pink (C:0, M:50, Y:0, K:0).
- GRLB[Gray] Barcode scans as "GRLBV" (Violet) - Gray in this case was C:0, M:0, Y:0, K:50
- GRLB[Purple] (C:50, M:100, Y:0, K:0) scans as Pink
- GRLB[Reddish Pink] usually scans as GLRBP, but sometimes as BRPGL  (Reddish Pink is C:0, M:100, Y:50, K:0)



I feel confident that Black is the special color, and the firmware is throwing away the data instead of passing it over Bluetooth protocol. 

Sincerely,
—Tom

**Comment by mutesplash** [comment]
Teal is the next prefix

**Comment by tomalphin** [comment]
Do any of the TR codes trigger an action yet?  I'm assuming this was added with the August releases (ex: Donkey Kong)

**Comment by mutesplash** [comment]
I printed out the whole space after testing and no new codes are in it... but they all return values!

The pre-DK release 2.6.4 (5.5 firmware) scanned TR codes but I don't have any app installs that go further back to check.  Peach mis-scanning the new Balloon code and dumping --U-- to the console tipped me off to try a new prefix.  I had another mis-scan that had RT in it, so I threw TR on half my test sheet with the other half being completely ignored PR codes since it was the closest to blue and green in "value."
